language: go

go:
  - 1.15.6

services:
  - docker

env:
  - GO111MODULE=on

before_install:
  - docker build -t trackbot . -f ./docker/trackbot.dockerfile
  - docker build -t vetbot . -f ./docker/trackbot.dockerfile