language: go

go:
  - 1.15.6

services:
  - docker

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

env:
  global:
    - GO111MODULE=on
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_PROD=niftysoft-1024
    - CLUSTER=my-first-cluster-1
    - ZONE=us-central1-a

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
deploy:
  - provider: script
    script: chmod +x docker/container-build.sh && bash docker/container-build.sh
    skip_cleanup: true
    on:
      branch: main

# TODO: deploy to kubernetes clusuter when master is tagged.
