apiVersion: v1
kind: ConfigMap
metadata:
  name: github-vet-bot-acceptlist
data:
  accept.yml: |
    accept:
      fmt:
        - Print
        - Println
        - Printf
        - Sprint
        - Sprintf
        - Sprintln
        - Errorf
        - Fprintf
        - Fprintln
        - Fprint
        - Fscan
        - Fscanr
        - Fscanln
        - Sscan
        - Sscanf
        - Sscanln

